#!/bin/bash
if [ "$1" = "--version" ]; then
  echo "${TARGET}-gcc (GCC) 4.9 20140827 (prerelease)"
  echo "Copyright (C) 2014 Free Software Foundation, Inc."
else
  exec $thecc -Wno-unknown-warning-option "${@/-fno-var-tracking-assignments/}"
fi
